#!/usr/bin/env sh
ulimit -n unlimited
rm "db.sqlite3"
.venv/bin/python3 manage.py makemigrations
.venv/bin/python3 manage.py migrate
exec .venv/bin/gunicorn --reload --threads 4 -w 4 --log-level debug blog_api_server.wsgi
